name: FitNesse Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Make Maven wrapper executable
      run: chmod +x mvnw

    - name: Build project
      run: ./mvnw clean compile

    - name: Start FitNesse server in background
      run: |
        ./mvnw exec:java -Dexec.mainClass="fitnesseMain.FitNesseMain" \
          -Dexec.args="-p 8080 -e 0" \
          -Dexec.classpathScope=test &
        echo "Waiting for FitNesse to start..."
        sleep 30

    - name: Verify FitNesse is running
      run: |
        curl -f http://localhost:8080/ || (echo "FitNesse failed to start" && exit 1)

    - name: Run FitNesse test suite
      run: |
        # Run the test suite and capture the results
        curl -f "http://localhost:8080/CalculatorTests?suite&format=text" > test-results.txt
        cat test-results.txt

    - name: Check test results
      run: |
        # Check if tests passed by looking for failure indicators
        if grep -q "0 wrong" test-results.txt && ! grep -q "Errors occurred" test-results.txt; then
          echo "All tests passed!"
          exit 0
        else
          echo "Tests failed!"
          cat test-results.txt
          exit 1
        fi

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: fitnesse-test-results
        path: test-results.txt

    - name: Generate test summary
      if: always()
      run: |
        echo "## FitNesse Test Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        tail -20 test-results.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
