name: FitNesse Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Make Maven wrapper executable (Unix)
      if: runner.os != 'Windows'
      run: chmod +x mvnw

    - name: Build project and compile tests (Unix)
      if: runner.os != 'Windows'
      run: ./mvnw clean test-compile

    - name: Build project and compile tests (Windows)
      if: runner.os == 'Windows'
      run: .\mvnw.cmd clean test-compile

    - name: Prepare FitNesse directories
      run: |
        mkdir -p FitNesseRoot/files
        mkdir -p FitNesseRoot/RecentChanges
        mkdir -p FitNesseRoot/ErrorLogs

    - name: Download FitNesse standalone JAR with dependencies (Unix)
      if: runner.os != 'Windows'
      run: |
        ./mvnw dependency:copy-dependencies -DincludeScope=test -DoutputDirectory=libs

    - name: Download FitNesse standalone JAR with dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        .\mvnw.cmd dependency:copy-dependencies -DincludeScope=test -DoutputDirectory=libs

    - name: Start FitNesse server in background (Unix)
      if: runner.os != 'Windows'
      run: |
        CLASSPATH="libs/*:target/classes:target/test-classes"
        nohup java -cp "$CLASSPATH" fitnesseMain.FitNesseMain -p 8080 -e 0 -o > fitnesse.log 2>&1 &
        echo $! > fitnesse.pid
        echo "FitNesse server started with PID $(cat fitnesse.pid)"
        sleep 5
        echo "=== Initial FitNesse Log (first 30 lines) ==="
        head -30 fitnesse.log || echo "Log file not created yet"

    - name: Start FitNesse server in background (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        set CLASSPATH=libs/*;target/classes;target/test-classes
        start /B java -cp %CLASSPATH% fitnesseMain.FitNesseMain -p 8080 -e 0 -o > fitnesse.log 2>&1
        timeout /t 10 /nobreak
        echo === Initial FitNesse Log (first 30 lines) ===
        if exist fitnesse.log (
          powershell -Command "Get-Content fitnesse.log -Head 30"
        ) else (
          echo Log file not created yet
        )

    - name: Wait for FitNesse to be ready (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "Waiting for FitNesse to start..."
        for i in {1..60}; do
          if curl -f -s http://localhost:8080/ > /dev/null 2>&1; then
            echo "FitNesse is up and running!"
            exit 0
          fi
          if [ $((i % 10)) -eq 0 ]; then
            echo "=== FitNesse Log (last 10 lines) at attempt $i ==="
            tail -10 fitnesse.log 2>/dev/null || echo "Log not available"
          fi
          echo "Attempt $i/60: FitNesse not ready yet..."
          sleep 2
        done
        echo "FitNesse failed to start within 120 seconds"
        echo "=== Full FitNesse Log ==="
        cat fitnesse.log
        exit 1

    - name: Wait for FitNesse to be ready (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        Write-Host "Waiting for FitNesse to start..."
        for ($i = 1; $i -le 60; $i++) {
          try {
            $response = Invoke-WebRequest -Uri http://localhost:8080/ -UseBasicParsing -TimeoutSec 2 -ErrorAction SilentlyContinue
            if ($response.StatusCode -eq 200) {
              Write-Host "FitNesse is up and running!"
              exit 0
            }
          } catch {}
          if ($i % 10 -eq 0) {
            Write-Host "=== FitNesse Log (last 10 lines) at attempt $i ==="
            if (Test-Path fitnesse.log) { Get-Content fitnesse.log -Tail 10 } else { Write-Host "Log not available" }
          }
          Write-Host "Attempt $i/60: FitNesse not ready yet..."
          Start-Sleep -Seconds 2
        }
        Write-Host "FitNesse failed to start within 120 seconds"
        Write-Host "=== Full FitNesse Log ==="
        Get-Content fitnesse.log
        exit 1

    - name: Run FitNesse test suite (Unix)
      if: runner.os != 'Windows'
      run: |
        # Run the test suite and capture the results
        curl -f --http0.9 "http://localhost:8080/CalculatorTests?suite&format=text" > test-results.txt
        cat test-results.txt

    - name: Run FitNesse test suite (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        # Run the test suite and capture the results
        Invoke-WebRequest -Uri "http://localhost:8080/CalculatorTests?suite&format=text" -OutFile test-results.txt
        Get-Content test-results.txt

    - name: Check test results (Unix)
      if: runner.os != 'Windows'
      run: |
        # Check if tests passed by looking for failure indicators
        if grep -q "0 Failures" test-results.txt; then
          echo "All tests passed!"
          echo "Test summary:"
          grep "Tests," test-results.txt
          exit 0
        else
          echo "Tests failed!"
          cat test-results.txt
          exit 1
        fi

    - name: Check test results (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        # Check if tests passed by looking for failure indicators
        $content = Get-Content test-results.txt -Raw
        if ($content -match "0 Failures") {
          Write-Host "All tests passed!"
          Write-Host "Test summary:"
          Select-String -Path test-results.txt -Pattern "Tests,"
          exit 0
        } else {
          Write-Host "Tests failed!"
          Get-Content test-results.txt
          exit 1
        }

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: fitnesse-test-results-${{ matrix.os }}
        path: |
          test-results.txt
          fitnesse.log
          fitnesse-error.log

    - name: Generate test summary (Unix)
      if: always() && runner.os != 'Windows'
      run: |
        echo "## FitNesse Test Results (${{ matrix.os }})" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        if [ -f test-results.txt ]; then
          tail -20 test-results.txt >> $GITHUB_STEP_SUMMARY
        else
          echo "Test results file not found - tests may not have run" >> $GITHUB_STEP_SUMMARY
        fi
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Generate test summary (Windows)
      if: always() && runner.os == 'Windows'
      shell: powershell
      run: |
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "## FitNesse Test Results (${{ matrix.os }})"
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value '```'
        if (Test-Path test-results.txt) {
          Get-Content test-results.txt -Tail 20 | Add-Content -Path $env:GITHUB_STEP_SUMMARY
        } else {
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "Test results file not found - tests may not have run"
        }
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value '```'

    - name: Stop FitNesse server (Unix)
      if: always() && runner.os != 'Windows'
      run: |
        if [ -f fitnesse.pid ]; then
          kill $(cat fitnesse.pid) || true
        fi

    - name: Stop FitNesse server (Windows)
      if: always() && runner.os == 'Windows'
      shell: powershell
      run: |
        # Kill any java processes running FitNesse
        Get-Process java -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
